cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

# Utilities
brew 'wget'
brew 'stow'
# brew 'koekeishiya/formulae/yabai'

# Browsers
cask 'firefox'
cask 'firefox-developer-edition'

# E-mail
cask 'thunderbird'
cask 'protonmail-bridge'

# Messaging
cask 'telegram'
cask 'discord'

# Productivity
cask 'evernote'
cask 'libreoffice'

cask 'anki'

# Media
#  Ebooks
cask 'calibre'
cask 'yacreader'

#  Music
cask 'spotify'
cask 'clementine'
cask 'musicbrainz-picard'
# cask 'xld'

#  Video
cask 'vlc'

# cask 'handbrake'

#  Torrents
cask 'qbittorrent'

# Development
cask 'visual-studio-code'
cask 'pycharm'
cask 'atom'

cask 'iterm2'

cask 'mongodb-compass-community'

cask 'java'

brew 'git'
cask 'sourcetree'

cask 'docker'
brew 'kubernetes-cli'

brew 'python'
brew 'node'

brew 'clojure/tools/clojure'
brew 'leiningen'

cask 'godot'

# Design
cask 'inkscape'

# Infrastructure
cask 'appcleaner'

cask 'expressvpn'

cask 'dropbox'
cask 'google-backup-and-sync'

cask '1password'

# Mac App Store
brew 'mas'
mas 'Todoist', id: 585829637

# Fonts
#   Sans
cask 'font-poppins'
cask 'font-roboto'
# cask 'font-tomorrow' https://fonts.google.com/specimen/Tomorrow
#   Serif
# cask 'font-grenze'
cask 'font-crimson-text'
#   Monospace
cask 'font-fira-code'
