cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

# Internet & Convenience
cask 'expressvpn'
cask '1password'

cask 'dropbox'
cask 'google-backup-and-sync'

# Terminal
cask 'hyper'
brew 'zsh'
brew 'wget'
brew 'stow'

# Utilities
cask 'caffeine'

cask 'rectangle'


# Browsers
cask 'firefox'
cask 'firefox-developer-edition'


# E-mail
cask 'thunderbird'
cask 'protonmail-bridge'


# Messaging
cask 'telegram'
cask 'discord'


# Notes
cask 'evernote'


# Office
cask 'libreoffice'


# Learning
cask 'anki'

# Media
#  Ebooks
cask 'calibre'
cask 'yacreader'

#  Music
cask 'clementine'
cask 'spotify'

cask 'musicbrainz-picard'

# cask 'xld'


#  Video
cask 'vlc'

# cask 'handbrake'


#  Torrents
cask 'qbittorrent'


# Development
#  IDEs
cask 'visual-studio-code'
cask 'pycharm'
cask 'atom'

#  VCSs
brew 'git'
cask 'sourcetree'

#  Helpers
cask 'dash'

#  Languages & Runtimes
cask 'java'

brew 'python'
brew 'node'

brew 'clojure/tools/clojure'
brew 'leiningen'

#  Databases
cask 'mongodb-compass-community'

#  Containerization & Orchestration
cask 'docker'

brew 'kubernetes-cli'
cask 'virtualbox'
brew 'minikube'


#  Game Development
cask 'godot'


# Design
cask 'inkscape'


# Maintenance
cask 'appcleaner'


# Mac App Store
brew 'mas'
mas 'Todoist', id: 585829637

# Fonts
#   Sans
cask 'font-poppins'
cask 'font-roboto'
# cask 'font-tomorrow' https://fonts.google.com/specimen/Tomorrow
#   Serif
# cask 'font-grenze'
cask 'font-crimson-text'
#   Monospace
cask 'font-fira-code'
